#!/usr/bin/env python
from titan import devicemgmt

print ""
print "#### Status ####"
devicemgmt.status()

print ""
print "#### Register ####"
devicemgmt.register()

print ""
print "#### Status ####"
devicemgmt.status()

print ""
print "#### Unregister ####"
devicemgmt.unregister()

print ""
print "#### Status ####"
devicemgmt.status()

